version: '3'

# Containers we are going to run
services:
  minig:
    build:
      # Here we define that it should build from the current directory
      context: .
    environment:
      # Variables to connect to our Postgres server
      PGUSER: minigadmin
      PGPASSWORD: minigadmin
      PGDATABASE: minig_dev
      PGPORT: 5432
      # Hostname of our Postgres container
      PGHOST: db
    ports:
      - "4000:4000"
    depends_on:
      # The db container needs to be started before we start this container
      - db
  db:
    # We use the predefined Postgres image
    build:
      context: ./utils/.
    environment:
      # Set user/password for Postgres
      POSTGRES_USER: minigadmin
      POSTGRES_PASSWORD: minigadmin
    restart: always
